[package]
name = "desc-stats-rayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
incr_stats = "1.0.2"
rayon = "1.10.0"
