[package]
name = "data-prep-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
polars = { version = "0.38.3", features = ["lazy"] }
smartcore = "0.3.2"
